version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adminLogin
      - MYSQL_DATABASE=todo
      - MYSQL_USER=tonmoy
      - MYSQL_PASSWORD=tonmoyLogin

    ports:
      - 3306:3306
    
    volumes:
      - mysql-data:/var/lib/mysql
  
  app:
    build: .
    container_name: todo_app
    ports:
      - 3000:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=tonmoy
      - MYSQL_PASSWORD=tonmoyLogin
      - MYSQL_DATABASE=todo
      - MYSQL_PORT=3306
    depends_on:
      - "db"


volumes:
  mysql-data:
    driver: local
